import { Toolbox } from "@phosphor-icons/react";
import { EggCrack, MapTrifold, Skull} from "phosphor-react";

export const cat = [
  {id: 1,para: "/buildsmapper", nome: "Mapper", desc: "Build altamente eficiente em limpar rapidamente mapas / grandes grupos de monstros, usando habilidades que possuem uma grande área de efeito, por isso costumam dar menos dano em Bosses / Monstros Raros.", icone: <MapTrifold size={52} color="#3977db" weight="fill" />},
  {id: 2,para: "/buildsbosser", nome: "Bosser", desc: "Build focada em eliminar um único inimigo por vez, como Bosses do jogo, devido a natureza de como o dano é aplicado a build acaba sofrendo um pouco quando o assunto é limpar mapas / grandes grupos de monstros com eficiência.", icone: <Skull size={52} color="#ffffff" weight="fill" />},
  {id: 3,para: "/buildsallrounder", nome: "All-Rounder", desc: "Uma build que se encontra entre um Mapper é um Bosser, possui as qualidades de ambos os playstyles mas não são tão eficientes em lidar com desafios específicos quanto as builds altamente especializadas.", icone: <Toolbox size={52} color="#e50b0b" weight="fill" />},
  {id: 4,para: "/buildsnewbiefriendly", nome: "Newbie friendly", desc: "Build pra quem AINDA não tem DEDO!", icone: <EggCrack size={52} color="#eae31f" weight="fill"/>},
]

export const dataBuilds = [
  {id: 1, build: "Explosive Arrow Elementalist", pob: "https://pobb.in/nmIGoPsBmvO2", video: "https://youtu.be/x2U0lKR1HvQ", maker: "Palsteron", type: "allrounder"},
  {id: 2, build: "Toxic Rain Pathfinder", pob: "https://pobb.in/p7oXr0Waxywc", video: "https://youtu.be/KAcrchacF8g", maker: "Palsteron", type: "allrounder"},
  {id: 3, build: "Explosive Arrow Champion", pob: "https://pobb.in/-FuxgC3WT2fO", video: "https://youtu.be/9PSAQdTHAL0", maker: "Ziz", type: "allrounder"},
  {id: 4, build: "Divine Ire Totem Heirophant", pob: "https://pobb.in/Rpvj4sTT2vdS", video: "null", maker: "Tatiantel2", type: "allrounder"},
  {id: 5, build: "Storm Burst Totem Heirophant", pob: "https://pobb.in/Fr_0rDUmXvUW", video: "null", maker: "Tatiantel2", type: "allrounder"},
  {id: 6, build: "Creeping Frost Totem Heirophant", pob: "https://pobb.in/m4g9DqBB5o9l", video: "null", maker: "Tatiantel2", type: "allrounder"},
  {id: 7, build: "Lightning Conduit Elementalist", pob: "null", video: "https://www.pathofexile.com/forum/view-thread/3410006", maker: "Enki", type: "mapper"},
  {id: 8, build: "Spark Inquisitor", pob: "https://pobb.in/JEbz2CaWqr8k", video: "https://youtu.be/2v2tblTWPxA", maker: "Goratha", type: "mapper"},
  {id: 9, build: "Ice Nova Inquisitor", pob: "https://pobb.in/wQd4trogkwcz", video: "https://youtu.be/RttgaOvENe4", maker: "RelaxaGuto", type: "allrounder"},
  {id: 10, build: "Corrupting Fever Champion Wand", pob: "https://pobb.in/76Et32qnRj-C", video: "https://youtu.be/G32EhMi5oRk", maker: "Ruetoo", type: "mapper"},
  {id: 11, build: "Corrupting Fever Champion Dagger", pob: "https://pobb.in/scA0LiGJsPyv", video: "https://youtu.be/OErWujhNmto", maker: "Ruetoo", type: "mapper"},
  {id: 12, build: "Poison Concoction", pob: "https://pobb.in/XyzKt9tx_rTH", video: "https://youtu.be/QLV4kYhPcdk", maker: "Snobae", type: "mapper"},
  {id: 13, build: "Exsanguinate Poison", pob: "https://pobb.in/QQlwgqZcf3fU", video: "https://youtu.be/IF_QxQCr-uY", maker: "Ruetoo", type: "mapper"},
  {id: 14, build: "Exsanguinate Scion", pob: "https://pobb.in/T5VUC5C1pc_t", video: "https://www.pathofexile.com/forum/view-thread/3324458", maker: "pawelos13", type: "mapper"},
  {id: 14, build: "Poison Blade Vortex Pathfinder", pob: "", video: "", maker: "", type: ""},
]

export const dataFarms = [
  {id: 1, nome: "Harb / Strongbox / Essence", link: "https://poeplanner.com/a/jQX", tipo: "PebaLord"},
  {id: 2, nome: "Strongbox / Essence / Expedition", link: "https://poeplanner.com/a/jcW", tipo: "PebaLord"},
  {id: 3, nome: "Strongbox / Essence / ToRmEnTeD SpIiIiIirIIiIIiiiTs", link: "https://poeplanner.com/a/jcy", tipo: "PebaLord"},
  {id: 4, nome: "Essence / Expedition", link: "https://poeplanner.com/a/EtH", tipo: "Early Game"},
  {id: 5, nome: "Essence / Metamorph", link: "https://poeplanner.com/a/jZp", tipo: "Early Game"},
  {id: 6, nome: "Blight / Essence", link: "https://poeplanner.com/a/jgP", tipo: "Early Game"},
  {id: 7, nome: "Legion / Delirium", link: "https://poeplanner.com/a/j5m", tipo: "Early Game"},
  {id: 8, nome: "Beyond / Essence / Delirium / Heist", link: "https://poeplanner.com/a/j5M", tipo: "Early Game"},
  {id: 9, nome: "Essence / Heist / Strongbox", link: "https://poeplanner.com/a/jRL", tipo: "Early Game"},
  {id: 10, nome: "Essence / Bestiary / Harvest (Rock Lee)", link: "https://poeplanner.com/a/jJp", tipo: "Late Game"},
  {id: 11, nome: "Essence / Bestiary / Harvest", link: "https://poeplanner.com/a/jZD", tipo: "Late Game"},
  {id: 12, nome: "Ritual / Essence / Bestiary", link: "https://poeplanner.com/a/jZI", tipo: "Late Game"},
  {id: 13, nome: "Breach / Bestiary", link: "https://poeplanner.com/a/DJA", tipo: "Late Game"},
  {id: 14, nome: "Breach / Delirium", link: "https://poeplanner.com/a/DJU", tipo: "Late Game"},
  {id: 15, nome: "Breach / Expedition", link: "https://poeplanner.com/a/DJq", tipo: "Late Game"},
  {id: 16, nome: "Blight / Strongbox / Essence", link: "https://poeplanner.com/a/G71", tipo: "Late Game"},
  {id: 17, nome: "Blight / Strongbox", link: "https://poeplanner.com/a/DJK", tipo: "Late Game"},
  {id: 18, nome: "Blight / Essence / Strongbox", link: "https://poeplanner.com/a/GAm", tipo: "Late Game"},
  {id: 19, nome: "Legion / Breach", link: "https://poeplanner.com/a/DJv", tipo: "Late Game"},
  {id: 20, nome: "Ritual / Metamorph", link: "https://poeplanner.com/a/DJI", tipo: "Late Game"},
  {id: 21, nome: "Ritual / Expedition", link: "https://poeplanner.com/a/DJb", tipo: "Late Game"},
  {id: 22, nome: "Ritual / Bestiary", link: "https://poeplanner.com/a/DJa", tipo: "Late Game"},
  {id: 23, nome: "Expedition / Essence / Betrayal", link: "https://poeplanner.com/a/DZD", tipo: "Late Game"},
  {id: 24, nome: "Expedition / Essence / Stongbox", link: "https://poeplanner.com/a/GN3", tipo: "Late Game"},
  {id: 25, nome: "Breach / Abyss", link: "https://poeplanner.com/a/DZ7", tipo: "Late Game"},
  {id: 26, nome: "Heist / Strongbox / Essence", link: "https://poeplanner.com/a/DiF", tipo: "Late Game"},
  {id: 27, nome: "Harvest / Strongbox / Harbinger / Essence", link: "https://poeplanner.com/a/DwK", tipo: "Late Game"},
]

export const dataTools = [
  {id: 1, nome: "Path of Building - Planejador de Buildings", link: "https://pathofbuilding.community", tipo: "Ferramentas"},
  {id: 2, nome: "Leveling Guide Master - Assistente de Leveling", link: "https://github.com/JusKillmeQik/PoE-Leveling-Guide", tipo: "Ferramentas"},
  {id: 3, nome: "Awakened PoE Trade - Assistente de Trade e Price Check", link: "https://snosme.github.io/awakened-poe-trade/download", tipo: "Ferramentas"},
  {id: 4, nome: "PoE Overlay - Overlay com Map Check, Atalhos e Comandos", link: "https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/releases", tipo: "Ferramentas"},
  {id: 5, nome: "Chaos Recipe Enhancer - Overlay para ajudar  a fazer chaos recipe", link: "https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases", tipo: "Ferramentas"},
  {id: 6, nome: "PoE Lurker - Facilita o trade de compra e venda", link: "https://github.com/C1rdec/Poe-Lurker", tipo: "Ferramentas"},
  {id: 7, nome: "Exilence Next - Programa que ajuda a verificar o preço dos itens na stash", link: "https://github.com/viktorgullmark/exilence-next#download", tipo: "Ferramentas"},
  {id: 8, nome: "Exile Tools Gem Planner (Site que gera colinha de gemas para lvling)", link: "https://exile-tools.com/gemplanner/", tipo: "Sites"},
  {id: 9, nome: "PoE Wiki(Contém muita informação do jogo)", link: "https://www.poewiki.net/wiki/Path_of_Exile_Wiki", tipo: "Sites"},
  {id: 10, nome: "PoE Leveling(Um guia de leveling escrito baseado no guia do Zizaran)", link: "https://poe-leveling.com", tipo: "Sites"},
  {id: 11, nome: "Craft of Exile(Ajuda a simular e escolher os melhores crafts)", link: "https://www.craftofexile.com", tipo: "Sites"},
  {id: 12, nome: "PoE Lab(Exibe o layout atual de cada Labirinto e outras informações)", link: "https://www.poelab.com", tipo: "Sites"},
  {id: 13, nome: "PoE Map.Trade(Te ajuda a fazer bulk trade de mapas)", link: "https://poemap.trade", tipo: "Sites"},
  {id: 14, nome: "PoE Ninja(Overview de Builds e Economia)", link: "https://poe.ninja", tipo: "Sites"},
  {id: 15, nome: "PoE Antiquary(Basicamente um poe ninja voltado para economia, exibe gráficos dos preços de diversos itens)", link: "https://poe-antiquary.xyz", tipo: "Sites"},
  {id: 16, nome: "Hideout Showcase(Contém vários modelos prontos de hideouts para vc copiar e colar) ", link: "https://hideoutshowcase.com", tipo: "Sites"},
]